# Generated by Django 5.0.7 on 2024-09-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0002_product_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordereditem',
            old_name='Product',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Cart Stage'), (1, 'Order Confirmed'), (2, 'Order Processed'), (3, 'Order Delivered'), (4, 'Order Rejected')], default=0),
        ),
        migrations.AlterUniqueTogether(
            name='ordereditem',
            unique_together={('product', 'owner')},
        ),
    ]
