# Generated by Django 5.0.7 on 2024-08-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=200),
            preserve_default=False,
        ),
    ]
